// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQMni9prXLss-B1HJQyxZJCbVDWGgykY',
    appId: '1:512939605137:web:9810d4422ad6958b7f5330',
    messagingSenderId: '512939605137',
    projectId: 'checkin-14a92',
    authDomain: 'checkin-14a92.firebaseapp.com',
    storageBucket: 'checkin-14a92.appspot.com',
    measurementId: 'G-GWVHEZETSL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZ89R9W48QoTN8nLJU7y0kNFT0PPaZ-Y',
    appId: '1:512939605137:ios:e05a127c66b1d03c7f5330',
    messagingSenderId: '512939605137',
    projectId: 'checkin-14a92',
    storageBucket: 'checkin-14a92.appspot.com',
    androidClientId: '512939605137-t94utfjag2pejf4dctmstovj48r0g8fd.apps.googleusercontent.com',
    iosClientId: '512939605137-kju1o4u0n7bqq8crkbup6kobhcshd963.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQMni9prXLss-B1HJQyxZJCbVDWGgykY',
    appId: '1:512939605137:web:fad1c3cae4d5c90b7f5330',
    messagingSenderId: '512939605137',
    projectId: 'checkin-14a92',
    authDomain: 'checkin-14a92.firebaseapp.com',
    storageBucket: 'checkin-14a92.appspot.com',
    measurementId: 'G-6RPXYZGYBF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgZ89R9W48QoTN8nLJU7y0kNFT0PPaZ-Y',
    appId: '1:512939605137:ios:e05a127c66b1d03c7f5330',
    messagingSenderId: '512939605137',
    projectId: 'checkin-14a92',
    storageBucket: 'checkin-14a92.appspot.com',
    androidClientId: '512939605137-t94utfjag2pejf4dctmstovj48r0g8fd.apps.googleusercontent.com',
    iosClientId: '512939605137-kju1o4u0n7bqq8crkbup6kobhcshd963.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBjyr3iu0U9Kzdakablqow2eko0s5WKWQ',
    appId: '1:512939605137:android:6e2fe03f04e933cb7f5330',
    messagingSenderId: '512939605137',
    projectId: 'checkin-14a92',
    storageBucket: 'checkin-14a92.appspot.com',
  );

}